######################################################################
# PIMSim Configuration for Code Generation
# - You do not need to specify all the PIM command's name
#   except for the cmd_descr/def field.
# - All the specification follows the order described in cmd_descr/def
#######################################################################

type:
  mem: "GDDR6"        # ["LPDDR5", "HBM2", "", ] (supported by Ramulator 2.0)
  pim: "specialized"  # ["general", "specialized"]

cmd_descr:
  def:
    openning:
    [
      "ACT4_BG", "ACTAF_BG", "ACT4_BKS", "ACTAF4_BKS",
      "ACT16", "ACTAF16",
    ]
    closing:
    [
      "PRE4_BG", "PRE4_BKS",
    ]
    column:
    [
      "MACSB", "AFSB", "RDCP", "WRCP",
      "MAC4B_INTRA", "AF4B_INTRA", "EWMUL", "EWADD", "MAC4B_INTER", "AF4B_INTER",
      "MACAB", "AFAB", "WRAFLUT", "WRBK",
    ]
    REF-like:
    [
      ""
    ]
    non-bank:
    [
      "WRGB", "WRMAC", "WRBIAS", "RDMAC", "WRBK",
    ]
  target_scope:
    bank:
      list:
      [
        ""
      ]
    bankgroup:
      interleaved: False
      list:
      [

      ]
    rank:
      interleaved: False
      list:
      [

      ]
    channel:
      list:
      [

      ]

cmd_params:
  constraints:
  [
    ""
  ]
  latency:
  [
    ""
  ]